global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dns-shield-monitor'

scrape_configs:
  - job_name: 'dns-shield'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'dns-shield:8080' ]
        labels:
          service: 'dns-shield'
          component: 'main-app'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          service: 'prometheus'
          component: 'monitoring'

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka:8082' ]
        labels:
          service: 'kafka'
          component: 'messaging'

