global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "dns-filtering-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "dns-service:8080" ]
        labels:
          service: "dns-filtering"

  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "otel-collector"
    static_configs:
      - targets: [ "otel-collector:8889" ]
